version: "3.8"

x-pool-env:
  &pool-env
  DEFAULT_POOL_SIZE: ${DEFAULT_POOL_SIZE:-24}

x-airflow-env:
  &airflow-env
  PYTHONPATH: ${AIRFLOW_HOME}/src
  AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
  AIRFLOW_WEB_ADMIN_PWD: ${AIRFLOW_WEB_ADMIN_PWD}
  AIRFLOW_WEB_ADMIN_USER: ${AIRFLOW_WEB_ADMIN_USER}
  AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PWD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_SCHEMA}


x-conn-env:
  &conn-env
  DWH_CONN_ID: ${DWH_CONN_ID:-dwh}
  SCORE_API_CONN_ID: ${SCORE_API_CONN_ID:-live_score_api}

  AIRFLOW_DB_USER: ${AIRFLOW_DB_USER}
  AIRFLOW_DB_PWD: ${AIRFLOW_DB_PWD}
  AIRFLOW_DB_SCHEMA: ${AIRFLOW_DB_SCHEMA}
  AIRFLOW_DB_HOST: ${AIRFLOW_DB_HOST}
  AIRFLOW_DB_PORT: ${AIRFLOW_DB_PORT}

  DWH_USER: ${DWH_USER}
  DWH_PWD: ${DWH_PWD}
  DWH_SCHEMA: ${DWH_SCHEMA}
  DWH_HOST: ${DWH_HOST}
  DWH_PORT: ${DWH_PORT}
  DWH_EXTRA: ${DWH_EXTRA}

  SCORE_API_HOST: ${SCORE_API_HOST}
  SCORE_API_USER: ${SCORE_API_USER}
  SCORE_API_PWD: ${SCORE_API_PWD}

networks:
  airflow-etl:
    name: airflow-etl-${COMPOSE_PROJECT_NAME}

services:
  initdb:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    user: airflow
    restart: on-failure:10
    networks:
      airflow-etl:
    environment:
      <<: *conn-env
      <<: *airflow-env
    command: bash -c "
      sleep 10;
      airflow db init;
      ./users.sh;
      ./connections.sh;"